#  app/alembic/alembic_utils.py

def include_object(object, name, type_, reflected, compare_to):
    """
    Exclude NocoDB tables from Alembic autogenerated migrations.
    """
    if type_ == "table" and name.startswith("nc_"):
        return False  # Exclude NocoDB tables
    return True  # Include all other objects