#  Copyright (c) 2022 Robert Bosch Manufacturing Solutions GmbH
#
#  See the AUTHORS file(s) distributed with this work for additional
#  information regarding authorship.
#
#  This Source Code Form is subject to the terms of the Mozilla Public
#  License, v. 2.0. If a copy of the MPL was not distributed with this
#  file, You can obtain one at https://mozilla.org/MPL/2.0/.
#
#   SPDX-License-Identifier: MPL-2.0


name: Neon-Stdio-Holi-T25-frontend CI

on:
  push:
    branches:
      - github-action-workflow
      - master
      - holi-t25-1.1.2  # Trigger workflow on `holi-t25-1.1.2`
    paths:
     - '.github/workflows/**' 
  workflow_dispatch:
    inputs:
      environment:
        description: "Frontend CI environment (staging or production)"
        required: true
        type: choice
        default: github-action-workflow
        options:
          - github-action-workflow
          - master
          - holi-t25-1.1.2  # Optionally, you can add `holi-t25-1.1.2` here if needed

permissions:
  contents: read
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout only the `frontend` folder using sparse-checkout
      - name: Checkout Neon-Studio-Holi-T25/frontend folder
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          
      - name: Enable sparse-checkout
        run: |
          git sparse-checkout init --cone
          git sparse-checkout set Neon-Stdio-Holi-T25/frontend

      - name: Verify Sparse Checkout
        run: |
          echo "Checked out directory: $(pwd)"
          echo "List of checked-out files: $(ls -a)"
          ls -R ${pwd}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Print Node.js version
        run: |
          echo "Node.js version: $(node --version)"
          echo "Installed Node.js version: $(npm --version)"

      - name: Install globally npm
        run: |
            npm i -g yarn
            echo "Installed globally npm: $(npm --version)"
            
      # Cache the npm/yarn dependencies
      - name: Cache npm and yarn dependencies
        id: cache-npm-yarn
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.yarn-cache
            Neon-Stdio-Holi-T25/frontend/node_modules  # Cache node_modules inside `frontend` folder
          key: ${{ runner.os }}-node-${{ hashFiles('**/Neon-Stdio-Holi-T25/frontend/package-lock.json', '**/Neon-Stdio-Holi-T25/frontend/yarn.lock') }}-${{ hashFiles('**/Neon-Stdio-Holi-T25/frontend/neon-studioz/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node- 

      - name: Show Cache Details
        run: |
          echo "Cache key used: ${{ steps.cache-npm-yarn.outputs.cache-hit }}"
          if [ "${{ steps.cache-npm-yarn.outputs.cache-hit }}" == 'true' ]; then
            echo "Cache hit! The following cache paths were restored:"
            echo "- ~/.npm"
            echo "- ~/.yarn-cache"
            echo "- Neon-Stdio-Holi-T25/frontend/node_modules"
          else
            echo "Cache miss! A new cache will be created with the following paths:"
            echo "- ~/.npm"
            echo "- ~/.yarn-cache"
            echo "- Neon-Stdio-Holi-T25/frontend/node_modules"
          fi

      - name: Install dependencies in frontend/neon-studioz
        run: |
            cd Neon-Stdio-Holi-T25/frontend/neon-studioz
            yarn install
            echo "Installed globally yarn: $(yarn --version)"
            echo "Installed dependencies in folder: ./Neon-Stdio-Holi-T25/frontend/neon-studioz"
            echo "Installed list of dependencies: $(yarn list --depth 0)"
            yarn list --depth 0
        working-directory: Neon-Stdio-Holi-T25/frontend/neon-studioz

      # Ensure cache is updated after installing dependencies
      - name: Update Cache After Installation
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ~/.yarn-cache
            Neon-Stdio-Holi-T25/frontend/node_modules  # Cache node_modules inside `frontend` folder
          key: ${{ runner.os }}-node-${{ hashFiles('**/Neon-Stdio-Holi-T25/frontend/package-lock.json', '**/Neon-Stdio-Holi-T25/frontend/yarn.lock') }}-${{ hashFiles('**/Neon-Stdio-Holi-T25/frontend/neon-studioz/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set timestamp
        id: set-timestamp
        run: echo "timestamp=$(date '+%Y-%m-%d-%H-%M-%S')" >> $GITHUB_ENV
